'use client';
import type { Metadata } from 'next'
import './globals.css'
import NavBar from './components/_NavBar';
import { ThemeProvider } from 'next-themes';
import Home from './page';
/*export const metadata: Metadata = {
  title: 'Ingila-Portfolio',
  description: 'Generated by Next14.0.1',
}*/

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en">
    <body >
    <ThemeProvider attribute='class'>
    <NavBar />
    <main className='h-screen flex flex-wrap items-left justify-left'>
        {children}
        </main>
      </ThemeProvider>   
      </body>
  </html>
  )
}
