'use client';
import type { Metadata } from 'next'
import './globals.css'
import NavBar from './components/_NavBar';
import { ThemeProvider } from 'next-themes';
/*export const metadata: Metadata = {
  title: 'Ingila-Portfolio',
  description: 'Generated by Next14.0.1',
}*/

export default function RootLayout({children}: {children: React.ReactNode}) {
  return (
    <html lang="en" className = "dark">
    <body className='dark:bg-gradient-to-b from-black  to-gray-700'>
    <ThemeProvider attribute='class' defaultTheme='light'>
    <main className=' min-h-screen min-w-screen ' >
    <NavBar/>

        {children}
        </main>
      </ThemeProvider>   
      </body>
  </html>
  )
}
